# Generated by Django 2.0.2 on 2018-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=2000)),
                ('location', models.CharField(max_length=1000)),
                ('emergency_level', models.IntegerField(choices=[('1', 'LEVEL 1'), ('2', 'LEVEL 2'), ('3', 'LEVEL 3')], default='1')),
            ],
        ),
    ]
