# Generated by Django 2.0.2 on 2018-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180302_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='detail',
            field=models.TextField(default='help me code', max_length=10000),
            preserve_default=False,
        ),
    ]
