# Generated by Django 2.0.2 on 2018-03-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180321_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='latitude',
            field=models.FloatField(default=103.68313469999998),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='longitude',
            field=models.FloatField(default=1.3483099),
        ),
    ]
