# Generated by Django 2.0.2 on 2018-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_incidentreport_nric'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='nric',
            field=models.CharField(default='S9539503B', max_length=10),
            preserve_default=False,
        ),
    ]
